# Generated by Django 2.1.5 on 2019-05-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('mess_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('reg_userName', models.CharField(max_length=50)),
                ('reg_passWord', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
