# Generated by Django 2.1.5 on 2019-05-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='mess_time',
            new_name='create_time',
        ),
    ]
